[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[font]
size = 11
bold = { family = "Mononoki Nerd Font Propo", style = "Bold"}
italic = { family = "Mononoki Nerd Font Propo",style = "Italic"}
normal = { family = "Mononoki Nerd Font Propo" ,style = "Regular"}
offset = { x = 0, y = 1}

[scrolling]
history = 10000
multiplier = 3

# [shell]
# args = ["-l", "-c", "tmux attach || tmux"]
# program = "/bin/zsh"

[window]
decorations = "None"
dynamic_title = false
opacity = 0.95

[window.padding]
x = 2
y = 2
