[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[font]
size = 14
normal = { family = "Mononoki Nerd Font Propo", style = "Regular" }
bold = { family = "Mononoki Nerd Font Propo", style = "Bold" }
italic = { family = "Mononoki Nerd Font Propo", style = "Italic" }
bold_italic = { family = "Mononoki Nerd Font Propo", style = "Bold Italic" }

[font.offset]
x = 0
y = 2

[scrolling]
history = 10000
multiplier = 3

# [shell]
# args = ["-l", "-c", "tmux attach || tmux"]
# program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_title = false
opacity = 0.95
padding = { x = 4, y = 4 }
# blur = true
