local kinds = require("xitiz.symbols")


local opts = {
    highlight_hovered_item = false,
    show_guides = true,
    auto_preview = false,
    position = 'right',
    relative_width = true,
    width = 16,
    auto_close = false,
    show_numbers = true,
    show_relative_numbers = true,
    show_symbol_details = false,
    preview_bg_highlight = 'Pmenu',
    autofold_depth = 3,
    auto_unfold_hover = true,
    fold_markers = { '', '' },
    wrap = false,
    keymaps = { -- These keymaps can be a string or a table for multiple keys
        close = { "<Esc>", "q" },
        goto_location = "<Cr>",
        focus_location = "o",
        hover_symbol = "<C-space>",
        toggle_preview = "K",
        rename_symbol = "r",
        code_actions = "a",
        fold = "h",
        unfold = "l",
        fold_all = "W",
        unfold_all = "E",
        fold_reset = "R",
    },
    lsp_blacklist = {},
    symbol_blacklist = {},
    symbols = {
        File = { icon = kinds["File"], hl = "@text.uri" },
        Module = { icon = kinds["Module"], hl = "@namespace" },
        Namespace = { icon = kinds["Namespace"], hl = "@namespace" },
        Package = { icon = kinds["Package"], hl = "@namespace" },
        Class = { icon = kinds["Class"], hl = "@type" },
        Method = { icon = kinds["Method"], hl = "@method" },
        Property = { icon = kinds["Property"], hl = "@method" },
        Field = { icon = kinds["Field"], hl = "@field" },
        Constructor = { icon = kinds["Constructor"], hl = "@constructor" },
        Enum = { icon = kinds["Enum"], hl = "@type" },
        Interface = { icon = kinds["Interface"], hl = "@type" },
        Function = { icon = kinds["Function"], hl = "@function" },
        Variable = { icon = kinds["Variable"], hl = "@constant" },
        Constant = { icon = kinds["Constant"], hl = "@constant" },
        String = { icon = kinds["String"], hl = "@string" },
        Number = { icon = kinds["Number"], hl = "@number" },
        Boolean = { icon = kinds["Boolean"], hl = "@boolean" },
        Array = { icon = kinds["Array"], hl = "@constant" },
        Object = { icon = kinds["Object"], hl = "@type" },
        Key = { icon = kinds["Key"], hl = "@type" },
        Null = { icon = kinds["Null"], hl = "@type" },
        EnumMember = { icon = kinds["EnumMember"], hl = "@field" },
        Struct = { icon = kinds["Struct"], hl = "@type" },
        Event = { icon = kinds["Event"], hl = "@type" },
        Operator = { icon = kinds["Operator"], hl = "@operator" },
        TypeParameter = { icon = kinds["TypeParameter"], hl = "@parameter" },
        Component = { icon = "", hl = "@function" },
        Fragment = { icon = "", hl = "@constant" },
    },

}

require("symbols-outline").setup(opts)
