- name: Sets zsh as default shell for my user | command
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ lookup('env', 'USER') }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: Check if oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_result

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" -y
  when: not oh_my_zsh_result.stat.exists

- name: Check if zsh-syntax-highlighting exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  register: has_zsh_syntax_highlighting

- name: Install zsh-syntax-highlighting
  when: not has_zsh_syntax_highlighting.stat.exists
  shell: |
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

- name: Check if zsh-autosuggestions exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  register: has_zsh_autosuggestions

- name: Install zsh-autosuggestions
  when: not has_zsh_autosuggestions.stat.exists
  shell: |
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: Check if zsh-autosuggestions exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/poetry
  register: has_poetry_zsh

- name: create oh-my-zsh poetry plugin folder
  file:
    path: ~/.oh-my-zsh/custom/plugins/poetry/
    state: directory
  when: not has_poetry_zsh.stat.exists

- name: Poetry zsh autocompletion
  shell: |
    poetry completions zsh > ~/.oh-my-zsh/custom/plugins/poetry/_poetry
  when: not has_poetry_zsh.stat.exists
