---

- name: Install ubuntu dependencies via apt-get
  package: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - cmake
    - software-properties-common
    - xbacklight

- name: Installing python (Debian/Ubuntu)
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-pip