-- Symbols taken from the lspkind defaults
local symbols = {
    Text = "󰉿",
    Method = "󰆧",
    Function = "󰊕",
    Constructor = "",
    Field = "󰜢",
    Variable = "󰀫",
    Class = "󰠱",
    Interface = "",
    Module = "",
    Property = "󰜢",
    Unit = "󰑭",
    Value = "󰎠",
    Enum = "",
    Keyword = "󰌋",
    Snippet = "",
    Color = "󰏘",
    File = "󰈙",
    Reference = "󰈇",
    Folder = "󰉋",
    EnumMember = "",
    Constant = "󰏿",
    Struct = "󰙅",
    Event = "",
    Operator = "󰆕",
    TypeParameter = "",
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
    FoldMarkerRight = "",
    FoldMarkerBottom = "",
    DebugBreakPoint = "",
    DebugStopped = "",
}

return symbols
