#!/bin/bash

pidof dunst && killall dunst
dunst -conf dunstrc &

notify-send -u low "message-one"
notify-send -u critical "message-two" "Lets write in a long messgae for the notifications"
notify-send "message-three" "another message"

dunstify -u low "message-four" "message body" -r 123
dunstify -u normal "message-four" "message body replaced" -r 123
dunstify  --hints=int:value:"50%" "SmartTech101" "Progressbar"
