#!/bin/bash

pidof dunst && killall dunst
dunst &

dunstify -u low "message-one"
dunstify -u critical "message-two" " this is the body"
dunstify "message-three"
dunstify "message-four"
dunstify "message-five"
dunstify "message-six"

