# - name: Clone dotfiles repo
#   git:
#     repo: 'https://github.com/xitizmandal/dotfiles.git'
#     dest: ~/.dotfiles
#     update: yes
#     recursive: yes:

# - name: Install dotfiles specific
#   package:
#     name: "{{ item }}"
#     state: "latest"
#   become: yes
#   with_items:
#     # - autorandr
#     - dunst
#     # - i3
#     # - polybar
#     - rofi-wayland
#     - hyprland
#     - waybar

- import_tasks: symlinks.yml
  become: no
  vars:
    srcBase: "{{ lookup('env', 'HOME') }}"
    dstBase: "{{ lookup('env', 'HOME') }}"

# - name: Copy fonts
#   copy:
#     src: "~/.dotfiles/fonts/Mononoki"
#     dest: "/Library/Fonts/"
