# - name: Clone dotfiles repo
#   git:
#     repo: 'https://github.com/xitizmandal/dotfiles.git'
#     dest: ~/.dotfiles
#     update: yes
#     recursive: yes:

- import_tasks: symlinks.yml
  become: no
  vars:
    srcBase: "{{ lookup('env', 'HOME') }}"
    dstBase: "{{ lookup('env', 'HOME') }}"

# - name: Copy fonts
#   copy:
#     src: "~/.dotfiles/fonts/Mononoki"
#     dest: "/Library/Fonts/"
