---

- name: Create symlinks for public files
  file:
    src: "{{srcBase }}/.dotfiles/{{ item.src }}"
    dest: "{{ srcBase }}/{{ item.dst }}"
    state: link
    force: yes
  with_items:
    - { src: "alacritty/.config/alacritty", dst: ".config/alacritty"}
    - { src: "bat/.config/bat", dst: ".config/bat"}
    - { src: "nvim/.config/nvim", dst: ".config/nvim"}
    - { src: "ranger/.config/ranger", dst: ".config/ranger"}
    - { src: "tmux/.tmux.conf", dst: ".tmux.conf"}
    - { src: "zsh/.zshrc", dst: ".zshrc"}
    - { src: "zsh/.alias", dst: ".alias"}
    - { src: "zsh/themes/candy.zsh-theme", dst: ".oh-my-zsh/custom/themes/candy.zsh-theme"}
